name: Release GrimoireLab component

on:
  workflow_call:
    inputs:
      git_email:
        description: 'Git config email'
        type: string
        required: true
      git_name:
        description: 'Git config name'
        type: string
        required: true
      release_candidate:
        description: 'Create a release candidate version'
        type: string
        required: true
      module_name:
        description: 'Name of the module'
        type: string
        required: true
      module_repository:
        description: 'Repository of the module'
        type: string
        required: true
      module_directory:
        description: 'Location of the module in Grimoirelab'
        type: string
        required: true
    secrets:
      access_token:
        description: 'Token for updating repositories'
        required: true

    outputs:
      package_version:
        description: "Package version formatted for Poetry"
        value: ${{ jobs.release.outputs.package_version }}
      version:
        description: "Version number for the package"
        value: ${{ jobs.release.outputs.version }}
      notes:
        description: "Notes content for the package"
        value: ${{ jobs.release.outputs.notes }}
      changed_version:
        description: "The version changed was major (4), minor (2), patch (1) or not changed (0)"
        value: ${{ jobs.release.outputs.changed_version }}

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      package_version: ${{ steps.version.outputs.package_version }}
      notes: ${{ steps.notes.outputs.notes }}
      changed_version: ${{ steps.changed-version.outputs.changed }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Git config
        run: |
          git config --global user.email "${{ inputs.git_email }}"
          git config --global user.name "${{ inputs.git_name }}"

      - name: Configure repository credentials
        run: |
          git submodule set-url ${{ inputs.module_directory }} https://${{ secrets.access_token }}@github.com/${{ inputs.module_repository }}.git

      - name: Checkout submodule ${{ inputs.module_directory }}
        run: |
          git submodule update --init --remote ${{ inputs.module_directory }}
          cd ${{ inputs.module_directory }}
          git checkout master

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Install release-tools
        #TODO: Change to the latest version once the new release is created
        run: pip install git+https://github.com/Bitergia/release-tools.git#egg=release-tools

      - id: old-version
        name: Get old version
        run: |
          version=$(poetry version -s)
          echo "::set-output name=version::$version"
        working-directory: ${{ inputs.module_directory }}

      - id: update-dependencies
        name: Update package dependencies
        run: |
          poetry update --lock
          dep_updated=$(git diff poetry.lock | wc -l)
          echo "::set-output name=dep_updated::$dep_updated"
          if [ $dep_updated -gt 0 ]
          then
            git diff
            git add poetry.lock
            git commit -m "Update Poetry dependencies"
          fi
        working-directory: ${{ inputs.module_directory }}

      - id: semverup
        name: Update version number
        continue-on-error: true
        shell: bash {0}
        run: |
          if [ ${{ inputs.release_candidate }} == 'true' ]
          then
            rcArg='--pre-release'
          else
            rcArg=''
          fi
          version=$(semverup $rcArg)
          dep_updated=${{ steps.update-dependencies.outputs.dep_updated }}
          if [ -z $version ] && [ $dep_updated -gt 0 ]
          then
            echo "Dependencies updated, force new version"
            version=$(semverup --bump-version patch $rcArg)
            echo "::set-output name=forced_version::true"
          fi
          echo $version
          if [ -z $version ]; then exit 1; fi
        working-directory: ${{ inputs.module_directory }}

      - id: version
        name: Get current version
        run: |
          version=$(poetry version -s)
          package_version="${{ inputs.module_name }}@>=$version"
          echo "::set-output name=package_version::$package_version"
          echo "::set-output name=version::$version"
          echo $package_version
        working-directory: ${{ inputs.module_directory }}

      - id: changed-version
        name: Get the version changed
        run: |
          BUMP_MAJOR=4
          BUMP_MINOR=2
          BUMP_PATCH=1
          current=${{ steps.version.outputs.version }}
          old=${{ steps.old-version.outputs.version }}
          # Remove rc part
          current=${current%-*}
          old=${old%-*}
          currentArr=(${current//./ })
          oldArr=(${old//./ })
          if [ ${currentArr[0]} -gt ${oldArr[0]} ]
          then
            echo "::set-output name=changed::$BUMP_MAJOR"
            echo "Major"
          elif [ ${currentArr[1]} -gt ${oldArr[1]} ]
          then
            echo "::set-output name=changed::$BUMP_MINOR"
            echo "Minor"
          elif [ ${currentArr[2]} -gt ${oldArr[2]} ]
          then
            echo "::set-output name=changed::$BUMP_PATCH"
            echo "Patch"
          else
            echo "::set-output name=changed::0"
            echo "Not changed"
          fi

      - id: notes
        name: Generate release notes.
        if: steps.semverup.outcome == 'success' && steps.semverup.outputs.forced_version != 'true'
        run: |
          version=${{ steps.version.outputs.version }}
          notes "${{ inputs.module_name }}" $version --news --authors
          version_notes="$(cat releases/$version.md)"
          version_notes="${version_notes//$'\n'/'%0A'}"
          echo "::set-output name=notes::$version_notes"
        working-directory: ${{ inputs.module_directory }}

      - id: notes-forced-version
        name: Generate release notes for updated dependencies
        if: steps.semverup.outcome == 'success' && steps.semverup.outputs.forced_version == 'true'
        run: |
          version=${{ steps.version.outputs.version }}
          module_name=${{ inputs.module_name }}
          today=$(date -u "+%Y-%m-%d")
          cat << EOF > releases/$version.md
          ## $module_name $version - ($today)

          * Update Poetry's package dependencies
          EOF

          version_notes="$(cat releases/$version.md)"
          version_notes="${version_notes//$'\n'/'%0A'}"
          echo "::set-output name=notes::$version_notes"
        working-directory: ${{ inputs.module_directory }}

      - id: current_time
        name: Store current time to get the release workflow
        if: steps.semverup.outcome == 'success'
        run: |
          datetime=$(date +"%Y-%m-%dT%H:%M:%S%z")
          echo "::set-output name=datetime::$datetime"
          echo $datetime

      - id: publish
        name: Publish new version.
        if: steps.semverup.outcome == 'success'
        run: |
          if [ ${{ inputs.release_candidate }} == 'true' ]
          then
            publish ${{ steps.version.outputs.version }} "${{ inputs.git_name }} <${{ inputs.git_email }}>" --push origin --no-cleanup
          else
            publish ${{ steps.version.outputs.version }} "${{ inputs.git_name }} <${{ inputs.git_email }}>" --push origin
          fi
        working-directory: ${{ inputs.module_directory }}

      - id: wait-for-release
        name: Wait for release to finish.
        continue-on-error: true
        if: steps.publish.outcome == 'success'
        run: |
          url="https://api.github.com/repos/${{ inputs.module_repository }}/actions/workflows/release.yml/runs?created=>${{ steps.current_time.outputs.datetime }}"
          while true
          do
            workflows=$(curl -sS -H "Authorization: token ${{ secrets.access_token }}" $url)
            if [ $(echo $workflows | jq '.total_count') -eq 0 ]
            then
              echo "Release workflow did not start"
              sleep 60
              continue
            fi

            release_conclusion=$(echo $workflows | jq '.workflow_runs[0].conclusion')
            release_status=$(echo $workflows | jq '.workflow_runs[0].status')
            if [ $release_status = \"completed\" -a $release_conclusion = \"success\" ]
            then
              echo "Release completed!";
              break;
            elif [ $release_status = \"completed\" -a $release_conclusion != \"success\" ]
            then
              echo "Release failed!";
              exit 1;
            else
              echo $release_conclusion $release_status
              echo "Waiting for release..."
              sleep 60
            fi
          done

      - id: check-package-ready
        name: Wait for package ready in PyPI
        shell: bash
        if: steps.wait-for-release.outcome == 'success'
        run: |
          package="${{ inputs.module_name }}"
          version="${{ steps.version.outputs.version }}"
          # Format version 1.2.3-rc.1 to 1.2.3rc1
          versionNum=${version%-*}
          versionRC=${version#$versionNum}
          versionRC=${versionRC//[-.]/}
          currentVersion="${versionNum}${versionRC}"

          pip install --upgrade pip
          for i in $(seq 20)
          do
            pip index versions --pre $package > pip_versions.txt
            pipVersion=$(cat pip_versions.txt | head -n 1 | cut -f2 -d '(' | cut -f1 -d ')')
            echo "$currentVersion $pipVersion"
            if [ "$pipVersion" = "$currentVersion" ]
            then
              echo "Same version"
              exit 0
            fi
            echo "Wait for PyPI..."
            sleep 10
          done
          echo "Latest version doesn't match after several retries"
          exit 1

      - id: rollback
        name: Rollback last commit and remove tag
        if: steps.wait-for-release.outcome == 'failure'
        run: |
          dep_updated=${{ steps.update-dependencies.outputs.dep_updated }}
          if [ $dep_updated -gt 0 ]
          then
            git reset --hard HEAD~2
          else
            git reset --hard HEAD~1
          fi
          git push -f origin master
          git tag -d ${{ steps.version.outputs.version }}
          git push --delete origin ${{ steps.version.outputs.version }}

          # Force to fail
          exit 1
        working-directory: ${{ inputs.module_directory }}
